name: polyHack2021_SBB
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - matplotlib
  - numba
  - numpy
  - pandas
  - qt
  - scipy
  - requests
  - dash
  - dash_html_components